# K-Prototype Clustering

Target encoding and include LICENSE in timoklein?? 

## Preprocessing for K-Protoptype Clustering

In [1]:
import pandas as pd
from kmodes.kprototypes import KPrototypes
from sklearn.preprocessing import StandardScaler, LabelEncoder
import numpy as np

In [2]:
df = pd.read_csv('Data/cleaned_data.csv', usecols=lambda column: column != 'Saved')

In [3]:
# Identify numerical, categorical and binary columns
num_cols = ['NumberOfCharacters', 'DiffNumberOFCharacters', 'Man', 'Woman', 'Pregnant', 'Stroller', 'OldMan', 'OldWoman', 'Boy', 'Girl', 'Homeless', 'LargeWoman', 'LargeMan', 'Criminal', 'MaleExecutive', 'FemaleExecutive', 'FemaleAthlete', 'MaleAthlete', 'FemaleDoctor', 'MaleDoctor', 'Dog', 'Cat', 'Finance_access', 'ICT', 'Industry_activity', 'Overall_index', 'Research_and_development', 'Skills', 'Total', 'Males', 'Females', 'Passengers', 'Pedestrians']
cat_cols = ['AttributeLevel', 'ScenarioTypeStrict', 'CrossingSignal'] #Categorical columns that shouldn't be scaled: 'CrossingSignal'
binary_cols = ['PedPed', 'Barrier']
delete_cols = ['ResponseID', 'UserID'] # Delete high-cardinality columns


In [4]:
# Normalize the numerical columns
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [5]:
# Label encode the categorical columns
labelencoder = LabelEncoder()
for col in cat_cols:
    df[col] = labelencoder.fit_transform(df[col])

In [6]:
# Delete the other columns
df = df.drop(delete_cols, axis=1)

In [7]:
pd.set_option('display.max_columns', None)
df.head(10)

ExtendedSessionID  PedPed  Barrier  CrossingSignal  \
0    1425316635_327833569077076.0       0        1               0   
1   -1683127088_785070916172117.0       1        0               2   
2    -887960483_174929057557052.0       0        0               2   
3   2069688900_9887644874714294.0       0        1               0   
4         -835212059_2515956109.0       0        1               0   
5   -841718081_3084184331213722.0       0        0               2   
6  -1777681375_4278593194428872.0       0        0               2   
7         -722961631_3464412713.0       0        1               0   
8    610674727_4967821486078208.0       1        0               0   
9           1073329312_1329715248       0        1               0   

   AttributeLevel  ScenarioTypeStrict  NumberOfCharacters  \
0               9                   0            1.360290   
1               8                   6            1.360290   
2               4                   5            1.360290   
3               8                   6            1.360290   
4               0                   1           -1.349367   
5              10                   5            0.682875   
6               5                   3           -0.671953   
7               2                   1            1.360290   
8               2                   1            1.360290   
9               4                   5            0.682875   

   DiffNumberOFCharacters       Man     Woman  Pregnant  Stroller    OldMan  \
0               -0.475248 -0.538389 -0.538533 -0.229445 -0.224707  3.573005   
1                1.315394 -0.538389 -0.538533 -0.229445 -0.224707  1.609823   
2               -0.475248  1.097636 -0.538533 -0.229445  3.823225 -0.353360   
3                3.106036 -0.538389 -0.538533 -0.229445 -0.224707 -0.353360   
4               -0.475248 -0.538389  1.097518 -0.229445 -0.224707 -0.353360   
5               -0.475248 -0.538389 -0.538533 -0.229445 -0.224707 -0.353360   
6                2.210715 -0.538389 -0.538533 -0.229445 -0.224707  1.609823   
7               -0.475248 -0.538389  2.733568 -0.229445 -0.224707 -0.353360   
8               -0.475248 -0.538389  1.097518 -0.229445 -0.224707 -0.353360   
9               -0.475248  1.097636  1.097518 -0.229445 -0.224707  1.609823   

   OldWoman       Boy      Girl  Homeless  LargeWoman  LargeMan  Criminal  \
0  5.535642 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698 -0.224400   
1 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698  3.828749   
2 -0.353561 -0.344473 -0.344744 -0.281963    1.952645 -0.344698 -0.224400   
3  1.609506 -0.344473 -0.344744  2.109827   -0.344853 -0.344698 -0.224400   
4 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698 -0.224400   
5 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698 -0.224400   
6 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698 -0.224400   
7 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698 -0.224400   
8 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698 -0.224400   
9 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853 -0.344698  3.828749   

   MaleExecutive  FemaleExecutive  FemaleAthlete  MaleAthlete  FemaleDoctor  \
0      -0.309780        -0.310001      -0.353466    -0.353257      -0.28361   
1       2.531945        -0.310001       1.610808    -0.353257      -0.28361   
2      -0.309780        -0.310001       1.610808     1.609857      -0.28361   
3      -0.309780        -0.310001      -0.353466     1.609857      -0.28361   
4      -0.309780        -0.310001      -0.353466    -0.353257      -0.28361   
5      -0.309780        -0.310001      -0.353466    -0.353257      -0.28361   
6      -0.309780        -0.310001      -0.353466    -0.353257      -0.28361   
7      -0.309780        -0.310001       3.575083     1.609857      -0.28361   
8      -0.309780        -0.310001       5.539358     1.609857      -0.28361   
9      -0.309780        -0.310001      -0.353466    -0.353257    

In [8]:
# Group by 'ExtendedSessionID' and take the first value of each group
grouped = df.groupby('ExtendedSessionID').first()

# Take the first 41666 groups and get the unique ExtendedSessionIDs
unique_extended_session_ids = grouped.head(4166).index.tolist()

# Subset the original dataset using this list
subset_df = df[df['ExtendedSessionID'].isin(unique_extended_session_ids)]

# Optionally, reset the index of the subset DataFrame
subset_df.reset_index(drop=True, inplace=True)

# Display the shape of the subset DataFrame
print(subset_df.shape)

(103852, 39)


In [9]:
# Delete the 'ExtendedSessionID' column
subset_df = subset_df.drop('ExtendedSessionID', axis=1)

In [10]:
subset_df.head()

PedPed  Barrier  CrossingSignal  AttributeLevel  ScenarioTypeStrict  \
0       1        0               2               4                   5   
1       0        0               2              11                   3   
2       1        0               0               3                   4   
3       0        0               2              11                   4   
4       0        0               0               9                   0   

   NumberOfCharacters  DiffNumberOFCharacters       Man     Woman  Pregnant  \
0           -1.349367               -0.475248 -0.538389 -0.538533  3.746352   
1            0.005461                0.420073 -0.538389 -0.538533 -0.229445   
2           -1.349367               -0.475248 -0.538389 -0.538533 -0.229445   
3           -1.349367               -0.475248 -0.538389 -0.538533 -0.229445   
4            0.005461               -0.475248  2.733660 -0.538533 -0.229445   

   Stroller    OldMan  OldWoman       Boy      Girl  Homeless  LargeWoman  \
0 -0.224707 -0.353360 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853   
1  3.823225 -0.353360 -0.353561 -0.344473  1.954265 -0.281963   -0.344853   
2 -0.224707 -0.353360 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853   
3 -0.224707 -0.353360 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853   
4 -0.224707  1.609823 -0.353561 -0.344473 -0.344744 -0.281963   -0.344853   

   LargeMan  Criminal  MaleExecutive  FemaleExecutive  FemaleAthlete  \
0 -0.344698   -0.2244       -0.30978        -0.310001      -0.353466   
1  1.953956   -0.2244       -0.30978        -0.310001      -0.353466   
2 -0.344698   -0.2244       -0.30978         2.530975      -0.353466   
3 -0.344698   -0.2244       -0.30978        -0.310001      -0.353466   
4 -0.344698   -0.2244       -0.30978        -0.310001      -0.353466   

   MaleAthlete  FemaleDoctor  MaleDoctor       Dog    Cat  Finance_access  \
0    -0.353257      -0.28361   -0.283496 -0.295301 -0.295       -1.124908   
1    -0.353257      -0.28361   -0.283496 -0.295301 -0.295       -2.090011   
2    -0.353257      -0.28361   -0.283496 -0.295301 -0.295       -1.124908   
3    -0.353257      -0.28361    2.795157 -0.295301 -0.295       -2.090011   
4    -0.353257      -0.28361   -0.283496 -0.295301 -0.295        0.805297   

        ICT  Industry_activity  Overall_index  Research_and_development  \
0 -1.797752          -1.127144      -1.193506                 -0.638820   
1  1.798564          -1.127144      -1.193506                 -2.039048   
2 -1.797752          -1.127144      -1.193506                 -0.638820   
3  1.798564          -1.127144      -1.193506                 -2.039048   
4 -0.199389           0.063409       0.993408                  1.228151   

     Skills     Total     Males   Females  Passengers  Pedestrians  
0 -1.437005  2.224566  2.488994  1.094687    0.857704     1.773086  
1  0.189389  0.049496  0.124876  0.039186    0.312039     1.295837  
2 -1.437005  2.224566  2.488994  1.094687    0.857704     1.773086  
3  0.189389  0.049496  0.124876  0.039186    0.312039     1.295837  
4  0.189389  0.679380  0.512740  1.136907    0.440382     0.289869

In [11]:
# Convert DataFrame to NumPy array
np = subset_df.to_numpy()

# Specify the indices of categorical columns
cat_col_indices = [subset_df.columns.get_loc(col) for col in cat_cols]

In [12]:
print(np)

[[1.         0.         2.         ... 1.09468675 0.85770393 1.77308632]
 [0.         0.         2.         ... 0.03918618 0.31203885 1.29583688]
 [1.         0.         0.         ... 1.09468675 0.85770393 1.77308632]
 ...
 [1.         0.         2.         ... 1.13690677 0.44038202 0.28986903]
 [0.         0.         0.         ... 1.13690677 0.44038202 0.28986903]
 [0.         1.         0.         ... 1.09468675 0.85770393 1.77308632]]


## Fitting the data into the model

In [13]:
# Create the k-Prototypes model
kproto = KPrototypes(n_clusters= 5, init='Cao', random_state=42)

# Fit the model to your data
clusters = kproto.fit_predict(np, categorical=cat_col_indices)

# Add the cluster labels to your DataFrame
subset_df['Cluster'] = clusters

In [14]:
subset_df.head(50)

PedPed  Barrier  CrossingSignal  AttributeLevel  ScenarioTypeStrict  \
0        1        0               2               4                   5   
1        0        0               2              11                   3   
2        1        0               0               3                   4   
3        0        0               2              11                   4   
4        0        0               0               9                   0   
5        0        0               0               5                   6   
6        1        0               1               6                   4   
7        0        1               0              12                   0   
8        0        0               2              11                   3   
9        1        0               0               4                   5   
10       0        0               2              11                   3   
11       1        0               2              10                   5   
12       1        0               0              10                   5   
13       0        1               0               5                   6   
14       0        0               0              11                   1   
15       0        0               0              11                   1   
16       0        0               2               4                   5   
17       1        0               0               1                   2   
18       0        0               0               1                   2   
19       0        0               2              10                   5   
20       1        0               0               4                   5   
21       0        0               2               2                   1   
22       1        0               1               5                   6   
23       0        0               0               8                   6   
24       0        1               0               7                   2   
25       0        0               0               6                   4   
26       1        0               0               1                   2   
27       0        0               2               3                   4   
28       0        0               2               5                   6   
29       0        1               0               0                   1   
30       1        0               0               4                   5   
31       0        0               2               8                   6   
32       1        0               2               5                   6   
33       1        0               2               5                   6   
34       1        0               2               0                   1   
35       0        0               0               8                   6   
36       0        0               0              10                   5   
37       0        1               0               2                   1   
38       1        0               2              12                   0   
39       1        0               2              10                   5   
40       1        0               1              12                   0   
41       1        0               0              12                   0   
42       1        0               1               3                   4   
43       0        0               0               7                   2   
44       1        0               1               4                   5   
45       1        0               2               4                   5   
46       0        0               0               2                   1   
47       1        0               0               0                   1   
48       0        0               1               8                   6   
49       0        0               0               6                   4   

    NumberOfCharacters  DiffNumberOFCharacters       Man     Woman  Pregnant  \
0            -1.349367               -0.475248 -0.538389 -0.538533  3.746352   
1             0.00